table Calendar
	lineageTag: 07a579fb-6ef5-4428-bda2-ff88471579f8

	column Date
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 91fcbeba-ebc7-4133-b4bc-e9793a880630
		summarizeBy: none
		sourceColumn: Date
		isKey

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		lineageTag: de4dc32d-b693-4eaf-8177-f21aaae522a1
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: eb3abeb3-3635-4787-8efb-a6c43f611c14
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		lineageTag: 84e34d57-3921-44f3-a429-a7ade11a46a1
		summarizeBy: none
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column MonthName
		dataType: string
		lineageTag: 8f06d751-55ea-403a-aea2-d7c54d977992
		summarizeBy: none
		sourceColumn: MonthName
		sortByColumn: Month

		annotation SummarizationSetBy = Automatic

	column Day
		dataType: int64
		lineageTag: 434e7539-ff46-49ac-8283-79800ab4f2e7
		summarizeBy: none
		sourceColumn: Day

		annotation SummarizationSetBy = Automatic

	column DayOfWeek
		dataType: int64
		lineageTag: 65a655ae-5755-4dd7-a6be-74bf3b9a05f6
		summarizeBy: none
		sourceColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	column DayName
		dataType: string
		lineageTag: 18972cb5-6c76-48ff-83e8-829d87ed267b
		summarizeBy: none
		sourceColumn: DayName
		sortByColumn: DayOfWeek

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: b4ea61d7-f5d2-441e-aa93-e8919747af32

		level Year
			ordinal: 0
			column: Year
			lineageTag: 27d4e992-702b-4d03-8c9e-245ef8febf4b

		level Quarter
			ordinal: 1
			column: Quarter
			lineageTag: cbef2b72-16c9-446b-8e89-7c5a5a13a6fd

		level Month
			ordinal: 2
			column: MonthName
			lineageTag: 3c357a08-4956-437b-a833-c566febaf91c

		level Day
			ordinal: 3
			column: Day
			lineageTag: fe53977b-471a-4ae2-acf2-c807383e5cc1


	partition 'Calendar-5a9a9225-e61b-4be6-a906-969c9f04ce44' = m
		mode: import
		source =
				let
				    StartDate = #date(2020, 1, 1),
				    EndDate = #date(2030, 12, 31),
				    DayCount = Duration.Days(EndDate - StartDate) + 1,
				    DateList = List.Dates(StartDate, DayCount, #duration(1, 0, 0, 0)),
				    #"Date Table" = Table.FromList(DateList, Splitter.SplitByNothing(), {"Date"}, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Date Table", {{"Date", type date}}),
				    #"Added Year" = Table.AddColumn(#"Changed Type", "Year", each Date.Year([Date]), Int64.Type),
				    #"Added Quarter" = Table.AddColumn(#"Added Year", "Quarter", each "Q" & Text.From(Date.QuarterOfYear([Date]))),
				    #"Added Month" = Table.AddColumn(#"Added Quarter", "Month", each Date.Month([Date]), Int64.Type),
				    #"Added MonthName" = Table.AddColumn(#"Added Month", "MonthName", each Date.MonthName([Date], "en-US")),
				    #"Added Day" = Table.AddColumn(#"Added MonthName", "Day", each Date.Day([Date]), Int64.Type),
				    #"Added DayOfWeek" = Table.AddColumn(#"Added Day", "DayOfWeek", each Date.DayOfWeek([Date], Day.Monday) + 1, Int64.Type),
				    #"Added DayName" = Table.AddColumn(#"Added DayOfWeek", "DayName", each Date.DayOfWeekName([Date], "en-US"))
				in
				    #"Added DayName"

	annotation PBI_ResultType = Table
	annotation Copilot_DateTable = true
	annotation Copilot_TableDescription = Contains 8 columns: Date, Year, Quarter, Month, MonthName, Day, DayOfWeek, DayName.

